services:

  tailwind:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "${DOCKER_WEB_VOLUME:-.:/app}"
      - /app/node_modules
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - django