services:

  tailwind:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: "${DOCKER_ENV_MODE:-production}"
    env_file:
      - .env
    volumes:
      - "${DOCKER_WEB_VOLUME:-.:/app}"
      - /app/node_modules
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - django